In [1]:
import numpy as np
import pandas as pd

In [2]:
emnist_train = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-train.csv")
emnist_test = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-test.csv")

In [3]:
emnist_train

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  \
0       7  0    0    0    0    0    0    0    0    0  ...      0      0   
1      16  0    0    0    0    0    0    0    0    0  ...      0      0   
2      15  0    0    0    0    0    0    0    0    0  ...      0      0   
3      23  0    0    0    0    0    0    0    0    0  ...      0      0   
4      17  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88795  21  0    0    0    0    0    0    0    0    0  ...      0      0   
88796   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88797  23  0    0    0    0    0    0    0    0    0  ...      0      0   
88798  12  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
88794      0      0      0      0      0      0      0      0  
88795      0      0      0      0      0      0      0      0  
88796      0      0      0      0      0      0      0      0  
88797      0      0      0      0      0      0      0      0  
88798      0      0      0      0      0      0      0      0  

[88799 rows x 785 columns]

In [4]:
emnist_test

1  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.548  0.549  \
0       1  0    0    0    0    0    0    0    0    0  ...      0      0   
1       1  0    0    0    0    0    0    0    0    0  ...      0      0   
2       1  0    0    0    0    0    0    0    0    0  ...      0      0   
3       1  0    0    0    0    0    0    0    0    0  ...      0      0   
4       1  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
14794  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14795  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14796  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14797  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14798  19  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.550  0.551  0.552  0.553  0.554  0.555  0.556  0.557  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
14794      0      0      0      0      0      0      0      0  
14795      0      0      0      0      0      0      0      0  
14796      0      0      0      0      0      0      0      0  
14797      0      0      0      0      0      0      0      0  
14798      0      0      0      0      0      0      0      0  

[14799 rows x 785 columns]

In [5]:
train = emnist_train.to_numpy()
test = emnist_test.to_numpy()

In [6]:
X_train = train[:,1:]
X_test = test[:,1:]

In [7]:
Y_train = train[:,0]
Y_test = test[:,0]

In [8]:
X_train=X_train/255
X_test=X_test/255

In [9]:
Y_train

array([ 7, 16, 15, ...,  1, 23, 12])

In [16]:
Z_train= np.zeros((X_train.shape[0],len(np.unique(Y_train))))
Z_train.shape

(88799, 26)

In [17]:
for i in range(X_train.shape[0]):
    Z_train[i][Y_train[i]-1] = 1

Z_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
def function(X,W,b):
    z=np.dot(X,W)+b
    f = 1/(1+np.exp(-z))
    return f

def err(X,Y,W,b):
    err = function(X,W,b)-Y
    return err

def loss_function(X,Y,W,b):
    m=X.shape[0]
    f1 = np.log(function(X,W,b))
    f2 = np.log(1-function(X,W,b))
    loss = -np.sum(np.multiply(Y,f1)+np.multiply((1-Y),f2))
    loss = loss/m
    return loss

def gradient_compute(X,Y,W,b):
    m=X.shape[0]
    dj_dw = np.dot(X.T,err(X,Y,W,b))
    dj_dw = dj_dw/m
    
    dj_db = np.sum(err(X,Y,W,b),axis =0)/m
    
    return dj_dw,dj_db

def gradient_descent(X,Y,W,b,L,n):
    m=X.shape[0]
    
    for i in range(n):
        dj_dw = gradient_compute(X,Y,W,b)[0]
        dj_db = gradient_compute(X,Y,W,b)[1]
        W=W-L*dj_dw
        b=b-L*dj_db
        loss = loss_function(X,Y,W,b)
        print(i, loss)
        
    return W,b,loss

In [19]:
w_in = np.zeros((X_train.shape[1],Z_train.shape[1]))
b=0

In [21]:
w_final, b_final,loss =gradient_descent(X_train,Z_train,w_in,b,0.96,500)

0 19.163873303018473
1 17.06693255470727
2 14.970675801158828
3 12.876069640253512
4 10.785986161681567
5 8.710772667303832
6 6.698497629025698
7 4.953035282921196
8 3.743181397729368
9 3.1827245164398135
10 2.944923916890429
11 2.8337214312408987
12 2.7750083939680716
13 2.7333633150559025
14 2.698133510500792
15 2.6675874665986226
16 2.640235190867514
17 2.6158973982262297
18 2.5937729060854413
19 2.5737555155724308
20 2.5553610532546975
21 2.5385030545038387
22 2.5228861989672557
23 2.5084305730296124
24 2.494951360129189
25 2.4823738715420895
26 2.4705773035019085
27 2.459494598698227
28 2.449042589270014
29 2.4391639586955405
30 2.4297987512495838
31 2.420899979151747
32 2.4124230131669497
33 2.4043304313067924
34 2.3965883511229773
35 2.3891674168493346
36 2.3820415491923668
37 2.3751877837340825
38 2.3685857849538903
39 2.362217467877812
40 2.356066744884427
41 2.350119192723008
42 2.344361881464432
43 2.3387831302507363
44 2.3333723787035283
45 2.3281200172570844
46 2.323017288

In [23]:
Y_output = function(X_test,w_final,b_final)
Y_output

array([[1.30181144e-01, 4.98172148e-03, 1.14976951e-08, ...,
        3.81262756e-01, 5.73010746e-03, 5.56768792e-04],
       [3.63547890e-01, 6.30215503e-05, 8.11111190e-02, ...,
        2.23584718e-04, 4.25623645e-05, 1.94201938e-03],
       [1.92821653e-02, 5.67097936e-05, 8.20451265e-05, ...,
        3.12137616e-06, 2.06604987e-07, 2.75850920e-05],
       ...,
       [1.76416571e-02, 9.77604391e-02, 1.59907629e-04, ...,
        4.46029682e-05, 5.45566431e-06, 5.00491412e-04],
       [1.67335108e-02, 6.02446364e-02, 9.54737689e-03, ...,
        4.17144945e-03, 3.82938225e-03, 4.98840321e-03],
       [2.81369323e-01, 1.61941554e-03, 2.64060870e-02, ...,
        1.60422033e-02, 1.62902976e-04, 2.08177572e-03]])

In [25]:
max = Y_output.max(axis=1)
for i in range(X_test.shape[0]):
    for j in range(len(np.unique(Y_train))):
        if Y_output[i][j] == max[i]:
            Y_output[i][j] = 1
        else:
            Y_output[i][j] = 0
            
Y_output

array([[0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [26]:
Y_predicted = np.empty_like(Y_test)
for i in range(X_test.shape[0]):
    for j in range(len(np.unique(Y_train))):
        if Y_output[i][j]==1:
            Y_predicted[i]=j+1
            
Y_predicted

array([24,  1, 17, ..., 19, 10,  1])

In [27]:
def accuracy(yout,ytest):
    m = yout.shape[0]
    count=0
    for i in range(m):
        if yout[i]==ytest[i]:
            count+=1
            
    acc = count/m*100
    return acc

In [28]:
accuracy(Y_predicted,Y_test)

68.77491722413677