In [1]:
import numpy as np 
import pandas as pd

In [2]:
emnist_train = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-train.csv")
emnist_test = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-test.csv")

In [3]:
emnist_train

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  \
0       7  0    0    0    0    0    0    0    0    0  ...      0      0   
1      16  0    0    0    0    0    0    0    0    0  ...      0      0   
2      15  0    0    0    0    0    0    0    0    0  ...      0      0   
3      23  0    0    0    0    0    0    0    0    0  ...      0      0   
4      17  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
88794   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88795  21  0    0    0    0    0    0    0    0    0  ...      0      0   
88796   1  0    0    0    0    0    0    0    0    0  ...      0      0   
88797  23  0    0    0    0    0    0    0    0    0  ...      0      0   
88798  12  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.408  0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
88794      0      0      0      0      0      0      0      0  
88795      0      0      0      0      0      0      0      0  
88796      0      0      0      0      0      0      0      0  
88797      0      0      0      0      0      0      0      0  
88798      0      0      0      0      0      0      0      0  

[88799 rows x 785 columns]

In [4]:
emnist_test

1  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.548  0.549  \
0       1  0    0    0    0    0    0    0    0    0  ...      0      0   
1       1  0    0    0    0    0    0    0    0    0  ...      0      0   
2       1  0    0    0    0    0    0    0    0    0  ...      0      0   
3       1  0    0    0    0    0    0    0    0    0  ...      0      0   
4       1  0    0    0    0    0    0    0    0    0  ...      0      0   
...    .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
14794  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14795  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14796  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14797  19  0    0    0    0    0    0    0    0    0  ...      0      0   
14798  19  0    0    0    0    0    0    0    0    0  ...      0      0   

       0.550  0.551  0.552  0.553  0.554  0.555  0.556  0.557  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
14794      0      0      0      0      0      0      0      0  
14795      0      0      0      0      0      0      0      0  
14796      0      0      0      0      0      0      0      0  
14797      0      0      0      0      0      0      0      0  
14798      0      0      0      0      0      0      0      0  

[14799 rows x 785 columns]

In [5]:
train = emnist_train.to_numpy()
test = emnist_test.to_numpy()

In [6]:
X_train = train[:,1:]
X_test = test[:,1:]

In [7]:
Y_train = train[:,0]
Y_test = test[:,0]

In [8]:
X_train=X_train/255
X_test=X_test/255

In [ ]:
X_train = X_train.T
X_test = X_test.T


In [ ]:
Z_train= np.zeros((X_train.shape[0],len(np.unique(Y_train))))

In [16]:
for i in range(X_train.shape[0]):
    Z_train[i][Y_train[i]-1] = 1

Z_train = Z_train.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
Z_train.shape

(26, 88799)

In [152]:
W1.shape,b1.shape,W2.shape,b2.shape

((5, 784), (5, 1), (26, 5), (26, 1))

In [153]:
def function(X,W,b):
    a = 1/(1+np.exp(-(np.dot(W,X)+b)))
    return a

def forward_prop(X,W1,b1,W2,b2):
    A1 = function(X,W1,b1)
    A2  = function(A1,W2,b2)
    return A1,A2

In [194]:
def gradient_descent(X,Y,W1,b1,W2,b2,L,itr):
    for i in range(itr):
        m = X.shape[1]
        
        #forward
        A1 = 1/(1+np.exp(-(np.dot(W1,X)+b1)))
        A2 = 1/(1+np.exp(-(np.dot(W2,A1)+b2)))
        
        #loss
        f1 = np.log(A2)
        f2 = np.log(1-A2)
        loss = -np.sum(np.multiply(Y,f1)+np.multiply((1-Y),f2))/m
        
        #backward
        dj_dw2 = np.dot((A2-Y)*(A2*(1-A2)),A1.T)/m
        dj_db2 = np.dot((A2-Y)*(A2*(1-A2)),np.ones((m,1)))/m
        dj_dw1 = np.dot(np.dot(W2.T,(A2-Y)*(A2*(1-A2)))*(A1*(1-A1)),X_train.T)/m
        dj_db1 = np.dot(np.dot(W2.T,(A2-Y)*(A2*(1-A2)))*(A1*(1-A1)),np.ones((m,1)))/m
        
        #updating
        W2 = W2 - L*dj_dw2
        b2 = b2 - L*dj_db2
        W1 = W1 - L*dj_dw1
        b1 = b1 - L*dj_db1
        
        print(i,loss)
    return W1,b1,W2,b2

In [199]:
n = 120
W1 = np.random.rand(n,784)-0.5
b1 = np.vstack(np.random.rand(n))-0.5
W2 = np.random.rand(26,n)-0.5
b2 = np.vstack((np.random.rand(26)))-0.5

In [200]:
W1_final,b1_final,W2_final,b2_final = gradient_descent(X_train,Z_train,W1,b1,W2,b2,0.5,3000)

0 26.225455288685144
1 12.623186078239897
2 8.17466787970876
3 5.61595128853045
4 4.990720735761759
5 4.816728320838429
6 4.715100793841381
7 4.6483785371424515
8 4.601749056304221
9 4.567806499022876
10 4.542368933800699
11 4.522881858456234
12 4.507694503830798
13 4.495693406025779
14 4.486101600009419
15 4.478361739211799
16 4.472064728358871
17 4.4669044056619995
18 4.462647807489802
19 4.45911510560586
20 4.456165740803119
21 4.453688635696243
22 4.451595157604476
23 4.449813974886481
24 4.448287241546277
25 4.446967729385168
26 4.4458166463984305
27 4.444801959031383
28 4.4438970890295915
29 4.443079891979682
30 4.4423318499116835
31 4.441637428150276
32 4.440983559325245
33 4.440359226645836
34 4.439755125262514
35 4.439163385499971
36 4.438577345442764
37 4.437991363135734
38 4.437400660770776
39 4.436801194843738
40 4.436189547506987
41 4.435562835306209
42 4.4349186322417165
43 4.434254904684915
44 4.4335699561473465
45 4.4328623802702305
46 4.432131020698619
47 4.43137493674

In [201]:
NN_output = forward_prop(X_test,W1_final,b1_final,W2_final,b2_final)[1]
NN_output = NN_output.T

In [202]:
NN_output.shape

(14799, 26)

In [203]:
max = NN_output.max(axis=1)
for i in range(X_test.T.shape[0]):
    for j in range(26):
        if NN_output[i][j] == max[i]:
            NN_output[i][j] = 1
        else:
            NN_output[i][j] = 0
            
NN_output

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [204]:
NN_predicted = np.empty_like(Y_test)
for i in range(X_test.T.shape[0]):
    for j in range(26):
        if NN_output[i][j]==1:
            NN_predicted[i]=j+1
            
NN_predicted


array([24,  3, 17, ..., 19, 10,  1])

In [205]:
def accuracy(yout,ytest):
    m = yout.shape[0]
    count=0
    for i in range(m):
        if yout[i]==ytest[i]:
            count+=1
            
    acc = count/m*100
    return acc

In [206]:
accuracy(NN_predicted,Y_test)

65.09223596188932